namespace Ocluse.LiquidSnow.Cryptography
{
    /// <summary>
    /// The type of ID to be generated by <see cref="CryptoUtility.GenerateId(IdKind, int)"/>
    /// </summary>
    public enum IdKind
    {
        /// <summary>
        /// Generates an ID based on <see cref="System.Guid"/>
        /// </summary>
        Guid,
        
        /// <summary>
        /// Generates a GUID that is transformed into an alphanumeric sequence.
        /// </summary>
        Standard,

        /// <summary>
        /// ID Generated by this method is simply the <see cref="Guid"/> but passed through SHA256 annotated in Hex format.
        /// </summary>
        Hash,

        /// <summary>
        /// Generates an ID based on the <see cref="System.DateTime"/>, conflicts may occur depending on the time, but are rare.
        /// </summary>
        DateTime,

        /// <summary>
        /// Generates an ID based on <see cref="System.Random"/>
        /// </summary>
        Random
    }
}
